import { Inter } from "next/font/google";
import "../globals.css";
import MainHeader from "@/components/HomePage/MainHeader";
import MainFooter from "@/components/HomePage/MainFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "webixel",
  description: "Generated by webixel.ir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
        <body className="font-iranYekan min-h-screen dark:bg-[#162F48]">
          <MainHeader />  
          {children}
          <MainFooter />
        </body>
    </html>
  );
}
